### PR TITLE
codeInputHighlightStyle apply for all fields issue fix

### PR DESCRIPTION
**Pull request by hasithaWalpola**

### CODE REVIEW

**Comment by isidoro98** [comment]
Could you please merge this? Highlight is not working as expected! @DavidHobbs @josinewong

**Comment by fpena** [comment]
Thanks for he PR! 
One question, you're removing something from PR #27. 
Is there a reason for that?

**Comment by isidoro98** [comment]
Yes, it's making the input highlighted when it's not on focus.

**Comment by fpena** [comment]
Can you please elaborate on that?
Reason is, we're removing something someone else added.

**Comment by hasithaWalpola** [comment]
Yeah, without this property the input code highlighted feature works. I mean the previous version. Remove it to work that feature as before. I checked all other things as well. No harm for any other feature and works perfectly. If you need more elaboration please let me know

**Comment by hasithaWalpola** [comment]
I think this was added to that clear input feature thing. Now it also works now without this condition in that line.

**Pull request merged**
